[package]
name = "corinth"
version = "0.1.0"
edition = "2024"
license = "MIT"
rust-version = "1.85"
repository = "https://github.com/SisyphusAeolides/Corinth"
description = "Transactional source and binary package manager for Arach OS"
build = "build.rs"

[features]
default = []
os-bin = []
fortran-policy = []
host-store = ["dep:libc"]

[dependencies]
sha2 = { version = "0.10.9", default-features = false }
slope = { git = "https://github.com/SisyphusAeolides/Slope.git", rev = "e1279f3a9c17638a70c55493b2851b011452a403" }
libc = { version = "=0.2.189", optional = true }

[lib]
path = "src/lib.rs"

[[bin]]
name = "corinth"
path = "src/main.rs"
required-features = ["os-bin"]
test = false

[lints.rust]
unsafe_op_in_unsafe_fn = "deny"
