[package]
name = "corinth"
version = "0.1.0"
edition = "2024"
license = "MIT"
rust-version = "1.85"
repository = "https://github.com/SisyphusAeolides/Corinth"
description = "Transactional source and binary package manager for Arach OS"
build = "build.rs"

[features]
default = []
os-bin = []
fortran-policy = []
host-store = ["dep:libc", "dep:arach-hwd", "dep:serde", "dep:toml"]

[dependencies]
sha2 = { version = "0.10.9", default-features = false }
slope = { git = "https://github.com/SisyphusAeolides/Slope.git", rev = "0982b44f3d7271903f827b4169cbf69b332a69ef" }
libc = { version = "=0.2.189", optional = true }
arach-hwd = { git = "https://github.com/SisyphusAeolides/Arach-HWD.git", rev = "a70f40e83e7ffc35b59362dcf0e04d0f3ae7983f", optional = true }
serde = { version = "=1.0.229", features = ["derive"], optional = true }
toml = { version = "=0.9.12", optional = true }

[lib]
path = "src/lib.rs"

[[bin]]
name = "corinth"
path = "src/main.rs"
test = false

[lints.rust]
unsafe_op_in_unsafe_fn = "deny"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
